# Generated by Django 3.0.6 on 2020-08-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_status_lose'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_word', models.CharField(max_length=20)),
            ],
        ),
    ]
