# Generated by Django 3.0.6 on 2020-08-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='word',
            new_name='word_name',
        ),
    ]
